[package]
name = "Kiosk"
version = "0.0.1"

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
Sui = { local = "/Users/nikos/Tools/sui-worktree/main/crates/sui-framework/packages/sui-framework" }

[addresses]
kiosk = "0x0"
